//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Controller Stuff/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""FishControls"",
            ""id"": ""c756280e-f599-423f-9746-14603da2a0cb"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""6e23ede9-9f40-46b7-b729-4a9c313298d6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Toggle Light"",
                    ""type"": ""Button"",
                    ""id"": ""6bd67fdc-43fd-4c34-bee3-09560897e39b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Flash"",
                    ""type"": ""Button"",
                    ""id"": ""46e5bf22-3eaf-437a-86a6-b507280d5de8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""93a520f9-0059-4750-8119-3bd4e4ca1a9b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Swap"",
                    ""type"": ""Button"",
                    ""id"": ""994a502a-9a23-4adc-a791-34a525b569a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""45b0cccd-6158-48be-8167-28539ae61ee7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Increase Light"",
                    ""type"": ""Button"",
                    ""id"": ""0a5cf21b-07a5-417b-aeab-33bad092da95"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Decrease Light"",
                    ""type"": ""Button"",
                    ""id"": ""6c467be1-d805-4fbe-adfc-47e59c864750"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""25680229-bc24-40c5-8240-a8daa64029c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dev Mode"",
                    ""type"": ""Button"",
                    ""id"": ""ede7f993-f411-441b-a889-abb94b3e01b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenDoors"",
                    ""type"": ""Button"",
                    ""id"": ""a2f05ae7-da4c-4db4-8238-d0b4ce5a674e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ce0582fc-7fbb-4e02-aa3a-0076ba0bd592"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""58dd7a7e-7dd0-46dd-93d4-566ed8feda81"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d07033ed-a44f-420b-9b8a-1b6daf1e57c2"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5ddc7314-6947-41b6-8dae-02a61a310475"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f058037c-fe7e-4ee7-b86a-23743f6524cd"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5233c80d-3778-499b-8c6d-00a75f1bfbd4"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9df0e515-db6b-49f2-baa9-68e370e02b3e"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b682ab9-c441-45ca-bfe1-df2d86ab1b37"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5e86912-e52b-485b-ab3b-58b767af9d1b"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d630477-ddc7-4382-9e84-f988f8387341"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3f8ddfc-df1a-4aeb-a72f-2f4a87f6d7a5"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d84cb781-5d87-4cbf-ad7d-20b09357c83f"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a70379dc-f946-491f-b005-872822e19a9f"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25028910-ac2c-4d09-a453-567d1c2e8f83"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf4c96b7-baad-4b54-96b3-375670308647"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Increase Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8175eeee-bcdf-4b67-8804-91507cb0ca71"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Increase Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72723c50-0e32-4656-8b85-761e4298d782"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Increase Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""373c9126-0717-4de9-8d39-029a35773ec4"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Decrease Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e2bbc1a-03b7-4de7-ac50-bf662eca6e01"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Decrease Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f89edfd8-faa9-45a7-9edb-9d398e0c3ac2"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Decrease Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ede16bff-435d-49b1-9267-9a40748aa6b5"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d77b7316-9607-4b33-8934-471cb4f76731"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78129ad7-b246-42a0-a921-67e1d69a894b"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f731352a-a502-4b85-b47e-c9211d364b61"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a157f1e6-33e0-49ce-a384-9fa33d1e9e94"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8537ec4-da4b-4e4d-b34c-5e64d476902c"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce153eaf-b151-4e0e-b70d-cd328c4f04bf"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dev Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04b12128-3b5c-4993-900a-37f06c2ae0b6"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenDoors"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""OctopusControls"",
            ""id"": ""61107d35-a1d9-4ba9-8d22-c39c8aa7036d"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""f70eef4c-4b5a-4a8c-a2ff-a220e56d6c19"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Strike"",
                    ""type"": ""Button"",
                    ""id"": ""15e946ac-65fb-4699-94c5-14eeb025f927"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""458e6de7-76ff-4775-88a7-49caf603c672"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Swap"",
                    ""type"": ""Button"",
                    ""id"": ""c2b9f2dd-1d97-4b60-b1c0-6a7a895fe90d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""9f2b1275-3f9b-4aa9-bf9f-734876fcb649"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""27f94ddd-9d36-4681-a4ca-7f9e8b69ca7f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dev Mode"",
                    ""type"": ""Button"",
                    ""id"": ""708d230f-65c8-470e-b758-e4d45546ad30"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenDoors"",
                    ""type"": ""Button"",
                    ""id"": ""47bbb653-8f53-459e-8256-519e3ee75297"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0b294ae7-eb56-49ca-a19d-c53daa27690e"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c90b287b-3b5b-4b77-9b4d-25c04a7a0499"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8c50e7ce-6762-438b-a2c4-444208c0342f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3ace11a4-311d-4392-80bf-9965813ccd99"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""859b14f9-fd78-4e80-a276-a7b7814e49b9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""38f2fd6a-9603-4313-8d73-f5a8144ed49e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""51bd55d0-bf83-4c49-9949-747d39d19107"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Strike"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""214a6418-0ed9-4ecb-a478-e2516ac1b0c9"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Strike"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e384d241-f8ff-432d-abad-30addc58c07c"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Strike"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8dc8441-f02b-4072-b359-2cc6de8c6682"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Strike"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03f39f37-ed37-4b77-bbbd-341ab678348c"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4731cda-924b-40b5-ab19-cfc45d24aa1f"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c9a64fb-f6d0-4eab-b94a-8169f9d73675"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a66692be-617b-4bef-9636-937deaa888d1"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""523c1010-bad3-487d-9c61-79981205df7d"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb6c25fd-adcc-4093-8a6c-b237dd56d88b"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1478e4a1-fa1c-4a14-96d8-a9f2c0eee304"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2cf9854-e1ab-48c1-99bd-76f908e7e35c"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""744724b3-c5a0-4073-a058-989635d3a833"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5495ac9c-5579-4aef-b67a-05e8971a581f"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9ea2431-ef5d-447d-b7a5-f68e2b653c7d"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dev Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3228b05-b220-4131-aee1-4a2a99528bcd"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenDoors"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MenuControls"",
            ""id"": ""c26dd8e3-f60a-4c81-940c-3ae2f4687597"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""007e2efc-55f3-4f74-9943-5346739401ef"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""32c1a3a4-c9fa-4278-a904-0b7071f80a5f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Go Back"",
                    ""type"": ""Button"",
                    ""id"": ""e36f4217-4870-4afe-a760-54a70ca5ca88"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8671bd97-244d-4e21-bf7a-5ba0ea6fb152"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""67317d6f-37e5-4a9c-ade6-6fda0ec1944e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d3818949-e70f-42eb-aff5-5b2a2a635984"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4f67dce3-2d12-4625-aab6-ec11e96e5e94"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bcb6d146-b7e8-4152-b3b3-58be22d84717"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""681d052f-cead-4ad9-a7c1-982394e3a569"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1e37aa28-71f6-4e9b-9e22-d51033a76a48"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b35b586e-2e46-462b-ba31-2a666b039a57"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""816879ad-5304-47c0-bdc0-8b3d73aa6295"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Go Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""406765e7-bab9-42d9-a433-9ed4a7cf6fad"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Go Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // FishControls
        m_FishControls = asset.FindActionMap("FishControls", throwIfNotFound: true);
        m_FishControls_Move = m_FishControls.FindAction("Move", throwIfNotFound: true);
        m_FishControls_ToggleLight = m_FishControls.FindAction("Toggle Light", throwIfNotFound: true);
        m_FishControls_Flash = m_FishControls.FindAction("Flash", throwIfNotFound: true);
        m_FishControls_Dash = m_FishControls.FindAction("Dash", throwIfNotFound: true);
        m_FishControls_Swap = m_FishControls.FindAction("Swap", throwIfNotFound: true);
        m_FishControls_Pause = m_FishControls.FindAction("Pause", throwIfNotFound: true);
        m_FishControls_IncreaseLight = m_FishControls.FindAction("Increase Light", throwIfNotFound: true);
        m_FishControls_DecreaseLight = m_FishControls.FindAction("Decrease Light", throwIfNotFound: true);
        m_FishControls_Select = m_FishControls.FindAction("Select", throwIfNotFound: true);
        m_FishControls_DevMode = m_FishControls.FindAction("Dev Mode", throwIfNotFound: true);
        m_FishControls_OpenDoors = m_FishControls.FindAction("OpenDoors", throwIfNotFound: true);
        // OctopusControls
        m_OctopusControls = asset.FindActionMap("OctopusControls", throwIfNotFound: true);
        m_OctopusControls_Move = m_OctopusControls.FindAction("Move", throwIfNotFound: true);
        m_OctopusControls_Strike = m_OctopusControls.FindAction("Strike", throwIfNotFound: true);
        m_OctopusControls_Dash = m_OctopusControls.FindAction("Dash", throwIfNotFound: true);
        m_OctopusControls_Swap = m_OctopusControls.FindAction("Swap", throwIfNotFound: true);
        m_OctopusControls_Pause = m_OctopusControls.FindAction("Pause", throwIfNotFound: true);
        m_OctopusControls_Select = m_OctopusControls.FindAction("Select", throwIfNotFound: true);
        m_OctopusControls_DevMode = m_OctopusControls.FindAction("Dev Mode", throwIfNotFound: true);
        m_OctopusControls_OpenDoors = m_OctopusControls.FindAction("OpenDoors", throwIfNotFound: true);
        // MenuControls
        m_MenuControls = asset.FindActionMap("MenuControls", throwIfNotFound: true);
        m_MenuControls_Move = m_MenuControls.FindAction("Move", throwIfNotFound: true);
        m_MenuControls_Select = m_MenuControls.FindAction("Select", throwIfNotFound: true);
        m_MenuControls_GoBack = m_MenuControls.FindAction("Go Back", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // FishControls
    private readonly InputActionMap m_FishControls;
    private IFishControlsActions m_FishControlsActionsCallbackInterface;
    private readonly InputAction m_FishControls_Move;
    private readonly InputAction m_FishControls_ToggleLight;
    private readonly InputAction m_FishControls_Flash;
    private readonly InputAction m_FishControls_Dash;
    private readonly InputAction m_FishControls_Swap;
    private readonly InputAction m_FishControls_Pause;
    private readonly InputAction m_FishControls_IncreaseLight;
    private readonly InputAction m_FishControls_DecreaseLight;
    private readonly InputAction m_FishControls_Select;
    private readonly InputAction m_FishControls_DevMode;
    private readonly InputAction m_FishControls_OpenDoors;
    public struct FishControlsActions
    {
        private @Controls m_Wrapper;
        public FishControlsActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_FishControls_Move;
        public InputAction @ToggleLight => m_Wrapper.m_FishControls_ToggleLight;
        public InputAction @Flash => m_Wrapper.m_FishControls_Flash;
        public InputAction @Dash => m_Wrapper.m_FishControls_Dash;
        public InputAction @Swap => m_Wrapper.m_FishControls_Swap;
        public InputAction @Pause => m_Wrapper.m_FishControls_Pause;
        public InputAction @IncreaseLight => m_Wrapper.m_FishControls_IncreaseLight;
        public InputAction @DecreaseLight => m_Wrapper.m_FishControls_DecreaseLight;
        public InputAction @Select => m_Wrapper.m_FishControls_Select;
        public InputAction @DevMode => m_Wrapper.m_FishControls_DevMode;
        public InputAction @OpenDoors => m_Wrapper.m_FishControls_OpenDoors;
        public InputActionMap Get() { return m_Wrapper.m_FishControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FishControlsActions set) { return set.Get(); }
        public void SetCallbacks(IFishControlsActions instance)
        {
            if (m_Wrapper.m_FishControlsActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnMove;
                @ToggleLight.started -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnToggleLight;
                @ToggleLight.performed -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnToggleLight;
                @ToggleLight.canceled -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnToggleLight;
                @Flash.started -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnFlash;
                @Flash.performed -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnFlash;
                @Flash.canceled -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnFlash;
                @Dash.started -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnDash;
                @Swap.started -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnSwap;
                @Swap.performed -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnSwap;
                @Swap.canceled -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnSwap;
                @Pause.started -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnPause;
                @IncreaseLight.started -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnIncreaseLight;
                @IncreaseLight.performed -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnIncreaseLight;
                @IncreaseLight.canceled -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnIncreaseLight;
                @DecreaseLight.started -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnDecreaseLight;
                @DecreaseLight.performed -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnDecreaseLight;
                @DecreaseLight.canceled -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnDecreaseLight;
                @Select.started -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnSelect;
                @DevMode.started -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnDevMode;
                @DevMode.performed -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnDevMode;
                @DevMode.canceled -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnDevMode;
                @OpenDoors.started -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnOpenDoors;
                @OpenDoors.performed -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnOpenDoors;
                @OpenDoors.canceled -= m_Wrapper.m_FishControlsActionsCallbackInterface.OnOpenDoors;
            }
            m_Wrapper.m_FishControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @ToggleLight.started += instance.OnToggleLight;
                @ToggleLight.performed += instance.OnToggleLight;
                @ToggleLight.canceled += instance.OnToggleLight;
                @Flash.started += instance.OnFlash;
                @Flash.performed += instance.OnFlash;
                @Flash.canceled += instance.OnFlash;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @Swap.started += instance.OnSwap;
                @Swap.performed += instance.OnSwap;
                @Swap.canceled += instance.OnSwap;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @IncreaseLight.started += instance.OnIncreaseLight;
                @IncreaseLight.performed += instance.OnIncreaseLight;
                @IncreaseLight.canceled += instance.OnIncreaseLight;
                @DecreaseLight.started += instance.OnDecreaseLight;
                @DecreaseLight.performed += instance.OnDecreaseLight;
                @DecreaseLight.canceled += instance.OnDecreaseLight;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @DevMode.started += instance.OnDevMode;
                @DevMode.performed += instance.OnDevMode;
                @DevMode.canceled += instance.OnDevMode;
                @OpenDoors.started += instance.OnOpenDoors;
                @OpenDoors.performed += instance.OnOpenDoors;
                @OpenDoors.canceled += instance.OnOpenDoors;
            }
        }
    }
    public FishControlsActions @FishControls => new FishControlsActions(this);

    // OctopusControls
    private readonly InputActionMap m_OctopusControls;
    private IOctopusControlsActions m_OctopusControlsActionsCallbackInterface;
    private readonly InputAction m_OctopusControls_Move;
    private readonly InputAction m_OctopusControls_Strike;
    private readonly InputAction m_OctopusControls_Dash;
    private readonly InputAction m_OctopusControls_Swap;
    private readonly InputAction m_OctopusControls_Pause;
    private readonly InputAction m_OctopusControls_Select;
    private readonly InputAction m_OctopusControls_DevMode;
    private readonly InputAction m_OctopusControls_OpenDoors;
    public struct OctopusControlsActions
    {
        private @Controls m_Wrapper;
        public OctopusControlsActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_OctopusControls_Move;
        public InputAction @Strike => m_Wrapper.m_OctopusControls_Strike;
        public InputAction @Dash => m_Wrapper.m_OctopusControls_Dash;
        public InputAction @Swap => m_Wrapper.m_OctopusControls_Swap;
        public InputAction @Pause => m_Wrapper.m_OctopusControls_Pause;
        public InputAction @Select => m_Wrapper.m_OctopusControls_Select;
        public InputAction @DevMode => m_Wrapper.m_OctopusControls_DevMode;
        public InputAction @OpenDoors => m_Wrapper.m_OctopusControls_OpenDoors;
        public InputActionMap Get() { return m_Wrapper.m_OctopusControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OctopusControlsActions set) { return set.Get(); }
        public void SetCallbacks(IOctopusControlsActions instance)
        {
            if (m_Wrapper.m_OctopusControlsActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnMove;
                @Strike.started -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnStrike;
                @Strike.performed -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnStrike;
                @Strike.canceled -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnStrike;
                @Dash.started -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnDash;
                @Swap.started -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnSwap;
                @Swap.performed -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnSwap;
                @Swap.canceled -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnSwap;
                @Pause.started -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnPause;
                @Select.started -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnSelect;
                @DevMode.started -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnDevMode;
                @DevMode.performed -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnDevMode;
                @DevMode.canceled -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnDevMode;
                @OpenDoors.started -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnOpenDoors;
                @OpenDoors.performed -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnOpenDoors;
                @OpenDoors.canceled -= m_Wrapper.m_OctopusControlsActionsCallbackInterface.OnOpenDoors;
            }
            m_Wrapper.m_OctopusControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Strike.started += instance.OnStrike;
                @Strike.performed += instance.OnStrike;
                @Strike.canceled += instance.OnStrike;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @Swap.started += instance.OnSwap;
                @Swap.performed += instance.OnSwap;
                @Swap.canceled += instance.OnSwap;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @DevMode.started += instance.OnDevMode;
                @DevMode.performed += instance.OnDevMode;
                @DevMode.canceled += instance.OnDevMode;
                @OpenDoors.started += instance.OnOpenDoors;
                @OpenDoors.performed += instance.OnOpenDoors;
                @OpenDoors.canceled += instance.OnOpenDoors;
            }
        }
    }
    public OctopusControlsActions @OctopusControls => new OctopusControlsActions(this);

    // MenuControls
    private readonly InputActionMap m_MenuControls;
    private IMenuControlsActions m_MenuControlsActionsCallbackInterface;
    private readonly InputAction m_MenuControls_Move;
    private readonly InputAction m_MenuControls_Select;
    private readonly InputAction m_MenuControls_GoBack;
    public struct MenuControlsActions
    {
        private @Controls m_Wrapper;
        public MenuControlsActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_MenuControls_Move;
        public InputAction @Select => m_Wrapper.m_MenuControls_Select;
        public InputAction @GoBack => m_Wrapper.m_MenuControls_GoBack;
        public InputActionMap Get() { return m_Wrapper.m_MenuControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuControlsActions set) { return set.Get(); }
        public void SetCallbacks(IMenuControlsActions instance)
        {
            if (m_Wrapper.m_MenuControlsActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_MenuControlsActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_MenuControlsActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_MenuControlsActionsCallbackInterface.OnMove;
                @Select.started -= m_Wrapper.m_MenuControlsActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_MenuControlsActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_MenuControlsActionsCallbackInterface.OnSelect;
                @GoBack.started -= m_Wrapper.m_MenuControlsActionsCallbackInterface.OnGoBack;
                @GoBack.performed -= m_Wrapper.m_MenuControlsActionsCallbackInterface.OnGoBack;
                @GoBack.canceled -= m_Wrapper.m_MenuControlsActionsCallbackInterface.OnGoBack;
            }
            m_Wrapper.m_MenuControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @GoBack.started += instance.OnGoBack;
                @GoBack.performed += instance.OnGoBack;
                @GoBack.canceled += instance.OnGoBack;
            }
        }
    }
    public MenuControlsActions @MenuControls => new MenuControlsActions(this);
    public interface IFishControlsActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnToggleLight(InputAction.CallbackContext context);
        void OnFlash(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnSwap(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnIncreaseLight(InputAction.CallbackContext context);
        void OnDecreaseLight(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnDevMode(InputAction.CallbackContext context);
        void OnOpenDoors(InputAction.CallbackContext context);
    }
    public interface IOctopusControlsActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnStrike(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnSwap(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnDevMode(InputAction.CallbackContext context);
        void OnOpenDoors(InputAction.CallbackContext context);
    }
    public interface IMenuControlsActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnGoBack(InputAction.CallbackContext context);
    }
}
